services:
  activemq-server:
    image: apache/activemq-classic:6.1.3
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - internal-net

  reports-service:
    build:
      context: .
      dockerfile: reports-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - activemq-server
    networks:
      - internal-net

  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - reports-service
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge